apiVersion: apps/v1
kind: Deployment
metadata:
  name: arash-backend
  namespace: grupp3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arash-guestbook
      component: backend
  template:
    metadata:
      labels:
        app: arash-guestbook
        component: backend
    spec:
      containers:
        - name: backend
          image: arashr/arash-guestbook:backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: arash-db-config
                  key: db-host
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: arash-db-config
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: arash-db-config
                  key: redis-port
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: arash-redis-password
                  key: password
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 20000m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: arash-backend
  namespace: grupp3
spec:
  type: ClusterIP
  selector:
    app: arash-guestbook
    component: backend
  ports:
    - port: 8080
